export const Country = [{ value: "BANGLADESH" }];
export const Gender = [{ value: "Male" }, { value: "Female" }];
export const City = [{ value: "CHATTOGRAM" }];
export const Locations = [
  { value: "Agrabad" },
  { value: "Chawkbazar" },
  { value: "Anderkilla" },
  { value: "GEC Circle" },
  { value: "Jamal Khan" },
  { value: "Khatunganj" },
  { value: "Kotwali" },
  { value: "New Market" },
  { value: "Reazuddin Bazar" },
  { value: "Sholashahar" },
  { value: "Panchlaish" },
  { value: "Nasirabad" },
  { value: "Muradpur" },
  { value: "Khulshi" },
  { value: "Pahartali" },
  { value: "Halishahar" },
  { value: "Probortak Hill" },
  { value: "VIP Colony" },
  { value: "Oxygen" },
  { value: "Agrabad Commercial Area" },
  { value: "Khatunganj Business Area" },
  { value: "Strand Road" },
  { value: "Karnaphuli Export Processing Zone (EPZ)" },
  { value: "Foy’s Lake" },
  { value: "Bakalia" },
  { value: "Chandgaon" },
  { value: "Bayezid Bostami" },
  { value: "Hathazari Road" },
  { value: "Riazuddin Bazar" },
  { value: "Karnaphuli Market" },
  { value: "Kaptai Road Market" },
  { value: "Bahaddarhat" },
  { value: "ChawkBazar" },
  { value: "Tamakumandi Lane" },
  { value: "Fishery Ghat" },
  { value: "DC Hill" },
  { value: "Lalkhan Bazar" },
  { value: "Dewanhat" },
  { value: "Railway Station Area" },
  { value: "Tiger Pass" },
  { value: "Port Colony" },
  { value: "Enayet Bazar" },
  { value: "Alkaran" }
];

export const TuitionCategories = [
  { value: "English Version" },
  { value: "Bangla Version" },
  { value: "British Curriculum" },
  { value: "Child Education" },
  { value: "Music" },
  { value: "Arts" },
  { value: "Admission Test Preparation" },
  { value: "Math Tutoring" },
  { value: "Science Tutoring" },
  { value: "Language Learning" },
  { value: "Coding for Kids" },
  { value: "Creative Writing" },
  { value: "Drawing & Painting" },
  { value: "Physical Education" },
  { value: "Public Speaking" },
  { value: "Soft Skills Development" },
  { value: "IELTS/TOEFL Preparation" },
  { value: "SAT/ACT Preparation" },
  { value: "Religious Studies" },
  { value: "Special Needs Education" },
  { value: "Homework Assistance" },
  { value: "Vocational Training" },
  { value: "Sports Coaching" },
  { value: "Dance Classes" },
  { value: "Photography & Videography" },
  { value: "Robotics & STEM" },
  { value: "Handwriting Improvement" },
  { value: "Career Counseling" }
];

export const TuitionType = [
  { value: "Home Tutoring" },
  { value: "Online Tutoring" },
  { value: "Group Tutoring" }
];
export const TutoringPerDaysInWeek = [
  { value: "1 days" },
  { value: "2 days" },
  { value: "3 days" },
  { value: "4 days" },
  { value: "5 days" },
  { value: "6 days" }
];
export const Class = [
  { value: "Play" },
  { value: "Nursery" },

  { value: "KG" },
  { value: "Standard One" },
  { value: "Standard Two" },
  { value: "Standard Three" },
  { value: "Standard FOUR" },
  { value: "Standard Five" },
  { value: "Standard Six" },
  { value: "Standard Seven" },
  { value: "Standard Eight" },
  { value: "Standard Nine" },
  { value: "Standard New Ten" },
  { value: "Arts Subject" },
  { value: "Science Subject" },
  { value: "Commerce Subject" },
  { value: "O level" },
  { value: "A LEVEL" },
  { value: "Public University Admission Test" },
  { value: "Private University Admission Test" },
  { value: "Medical University Admission Test" },
  { value: "Engineering University Admission Test" }
];
