import type { Metadata } from "next";
import NavBar from "../Components/Shared/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function CommonLayout({
  children
}: Readonly<{
  children: React.ReactNode;
  className?: string;
}>) {
  return (
    <div>
      <NavBar />
      {children}
    </div>
  );
}
