import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./Components/Shared/NavBar";
import Footer from "./Components/Shared/Footer";
import ProgressBar from "@/app/Components/Shared/ProgressBar";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900"
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900"
});

export const metadata: Metadata = {
  title: "HomeTutor",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <NavBar /> */}
        <div className="sticky customWidth mx-auto z-[999] top-0 ">
          <ProgressBar />
          <NavBar />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
