const LoginPageOfAdmin = () => {
  return (
    <div className="bg-red-800 w-full ">
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
      <h1>Login Page of Admin PAGE</h1>
    </div>
  );
};
export default LoginPageOfAdmin;
